version: '3'
services:

  spring-example-base-image:
      build: ./spring-example-base-image
      image: eventuateio/eventuate-examples-docker-images-spring-example-base-image:${DOCKER_IMAGE_TAG:?required DOCKER_IMAGE_TAG}
  micronaut-example-base-image:
      build: ./micronaut-example-base-image
      image: eventuateio/eventuate-examples-docker-images-micronaut-example-base-image:${DOCKER_IMAGE_TAG:?required DOCKER_IMAGE_TAG}
